### PR TITLE
Support Yosemite's dark mode with b&w icon

### PR DESCRIPTION
**Pull request by anujdas**

### CODE REVIEW

**Comment by rderharo** [comment]
I guess the likelihood of a 0.5.1 compiled release is out of the question?

**Comment by citruspi** [comment]
@rderharo,

Sorry for the long wait! I wanted to wait till I had finished the Swift re-write and just release that, but I kept getting sidetracked.

So, I've archived and signed a copy of both 0.5.0 and 0.5.1. I've added tags for both of them, and uploaded the binaries to the Releases page.

I've also updated [the website](http://spotify-notifications.citruspi.io) with the latest information and links.

&mdash; @citruspi

**Comment by rderharo** [comment]
Oh wow, thanks for the quick response! I'll give it a shot tonight.

**Comment by rderharo** [comment]
Unfortunately I cannot seem to launch 0.5.1. I downloaded it today and I get this error message when I try to launch it:

> "Spotify Notifications.app" is damaged and can't be opened. You should move it to the Trash."

**Pull request closed without merging**
