### PR TITLE
Revamped Preferences UI, tidied code

### PR DESCRIPTION
**Pull request by sebj**
Nice work on Spotify Notifications, I've been using it for a while and found it very useful! (I don't know why Spotify still doesn't have native Mac notifications..)

*Changes:*

**UI:**
I replaced the strange combo boxes in the Preferences window with checkboxes, and organised the window better:
Imgur Preview

A small addition is the ability to skip the current song (hover on notification to show button), like with iTunes:
Regular notification
Hover on notification

**Code:**
As for code, preferences are now updated and kept in sync via bindings, rather than manually calling methods/updating when the user clicks.

Code's a bit more concise/tidy by using dot-syntax; removing unnecessary `@synthesize` lines; defining a few shared keys for storing preferences in `SharedKeys.h` instead of repeating strings in code (with the possibility of mistakes); and marking code sections with `#pragma mark - Section Name` for easier navigation.

This uses #27, and solves #18, #23 and #53.

### CODE REVIEW

**Comment by sebj** [comment]
Edit: Critical problem I'm just fixing.

**Comment by citruspi** [comment]
> Nice work on Spotify Notifications, I've been using it for a while and found it very useful! (I don't know why Spotify still doesn't have native Mac notifications..)

Thanks! And yeah, I'm not sure why they have continued to ignore their OS X users who've requested the feature - especially when it shouldn't take more than a couple lines of code.

> I replaced the strange combo boxes in the Preferences window with checkboxes, and organised the window better

Awesome! That actually makes a lot of sense, I'm not sure why I used dropdowns when I could have used checkboxes.

> A small addition is the ability to skip the current song (hover on notification to show button), like with iTunes:

Super cool! Thanks for getting that implemented.

> As for code, preferences are now updated and kept in sync via bindings, rather than manually calling methods/updating when the user clicks.

> Code's a bit more concise/tidy by using dot-syntax; removing unnecessary `@synthesize` lines; defining a few shared keys for storing preferences in `SharedKeys.h` instead of repeating strings in code (with the possibility of mistakes); and marking code sections with `#pragma mark - Section Name` for easier navigation.

These changes look pretty great. If you haven't already realized, Objective-C isn't my strongest language and I probably miss a lot of best practices, so please feel free to fix anything that you think could be better.

---

I'm not sure if you're done with this pull request or still working on stuff, so let me know when these changes are complete and I'll do a review.

Also, if you have further changes that aren't related, multiple small pull requests are preferable to a single large one.

**Comment by sebj** [comment]
I have a commit or two to add – I'll leave another comment when I'm done.

I am sorry this turned into such a massive pull request with so many commits/such a long changelog! Only intended to make a UI change, but then looked over the code and felt like making a few tweaks.

I'll create separate pull-requests for less-related changes in future for sure.

**Comment by sebj** [comment]
Ready to merge this pull request with your approval. I'll leave changelog/version number to you.

**Comment by citruspi** [comment]
Thanks @sebj!

Unfortunately I won't have time to look at this until this weekend, but I'll ping you after I take a look!

**Comment by RowanKaag** [comment]
Can this get merged, please? :)

**Comment by kassio** [comment]
👍

**Comment by arbass22** [comment]
@citruspi I would be interested in contributing to this project/adding new features, but this seems like a fairly significant changeset so I'd probably want to wait until it is merged.

**Comment by nbgraham** [comment]
@citruspi Is this getting merged at some point?

**Comment by sebj** [comment]
Lesson to everyone, don't fork someone's repo and then refactor most of it suddenly. : | FeelsBad for @citruspi now.

**Comment by citruspi** [comment]
@sebj Which version of macOS did you develop and test this on?

I went to go cut the 0.6.0 release for #72  and I noticed some odd behavior on my macOS Sierra machine.

On macOS Sierra the notification has action buttons and doesn't disappear by itself - it needs to be closed manually. On macOS El Capitan, the notification doesn't have action buttons and disappears automatically. 

The action buttons themselves are fine, but I suspect they're causing the notifications to stick around as opposed to disappearing automatically. If that's the case, it might make sense to put them behind a feature toggle. 

### El Capitan: 


### Sierra:

**Comment by sebj** [comment]
I think it depends whether Spotify Notifications is set to use "Banners" or "Alerts" in the Notifications pane of System Preferences. I initially could not recreate your Sierra – for me it behaved the same on Sierra as it did in El Capitan (hover to see buttons, notification automatically dismisses). I went to System Preferences, changed Spotify Notifications from "Banners" to "Alerts" style and now I get the same behaviour as you. It may be that Sierra changed the default alert style? I'm not sure exactly..

**Comment by robinnorth** [comment]
I might be able to shed some light on this (long time user, first time poster). The `NSUserNotificationAlertStyle` key in [Spotify Notifications-Info.plist](https://github.com/citruspi/Spotify-Notifications/blob/master/Spotify-Notifications/Spotify%20Notifications-Info.plist) is set to `alert`, not `banner` (`banner` is the default, see: https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html).

That means that unless a user manually changes their Notification Center preferences for Spotify Notifications to 'Banners', they'll get the 'Alerts' style notification by default, which are persistent until dismissed, hence the additional 'Close' button they have. @citruspi, the action button on a 'Banners'-style notification only appears on mouseover. I can confirm it works correctly for me on Sierra.

**Comment by sebj** [comment]
@robinnorth There we go, thanks! Completely forgot about setting the value in the Info.plist.

**Comment by sebj** [comment]
@citruspi Merged @robinnorth's small PR in to fix this.

**Comment by robinnorth** [comment]
No problem, @sebj! Happy to be able to contribute (even if only in a small way) to a project that I use on a daily basis.

**Comment by citruspi** [comment]
@robinnorth Thanks for the contribution, it's been included in the version 0.6.0 release.

Thanks for taking care of the pull request @sebj.

**Pull request merged**
