### PR TITLE
Changes for successful build with Swift 3, XCode 8

### PR DESCRIPTION
**Pull request by nbgraham**
The project did not build when I first pulled it down.
I had to updated the Podfile and a few other syntax changes for Swift3.

Now the project builds and runs.

### CODE REVIEW

**Comment by sebj** [comment]
First up on the Swift todo list is this!

**Comment by nbgraham** [comment]
@sebj I'm trying to get it pass CI. It keeps failing on `pod install`.

**Comment by sebj** [comment]
So, based on the most recent commits to the `master` branch, I don't believe we need `Alamofire` or `SwiftyJSON` and could just use git submodule for `MASShortcut` and `NSBundle-LoginItem`. Got that much working at the moment, and I wanna get started on converting to Swift otherwise.

/cc @citruspi 

Edit: May have gotten stuck in.. Ported the entire project over to Swift 3 (+ Xcode 8) and got Travis working. Using a single git submodule for `MASShortcut`. Otherwise, complete feature parity & readme etc now match `master` branch.

**Comment by sebj** [comment]
Closed due to progress made in `swift-dev`

**Pull request closed without merging**
